### ISSUE TITLE
Tomcat can't run

### ISSUE THREAD

**Issue by leewheel** [Abd-ulRahman/FusionCMS_4_LC#1]
I installed JDK 19 64bit, but Tomcat can not running : Tomcat Started/Stopped with errors, return code: 1

**Comment by Abd-ulRahman** [comment]
I do offer support for fusion not technical support for operating system problems, on the other hand
What Operating System you are using???
Windows, Mac , [Ubuntu] etc....
and screen shot for the error needed

**Comment by leewheel** [comment]
I used your repack: https://www.mediafire.com/file/teuttc0lhy76231/WoW_Wotlk_Server_LC.exe/file 
I think this is a OS issues.

**Comment by Abd-ulRahman** [comment]
You did the right thing,
